### PR TITLE
1451 alignment off in the create post module post in 1 (2nd PR, 1st abandoned)

### PR DESCRIPTION
**Pull request by dcetlin**
https://github.com/Hylozoic/hylo-evo/assets/31668971/73b64c1b-c93f-4e0a-9031-48524d9630e9

Simple solution. I also realized why I screwed my last branch. I rebased on master instead of dev.

### CODE REVIEW

**Review by thomasgwatson — APPROVED** [review]
lgtm

**Comment by thomasgwatson** [comment]
@tibetsprague did you want to have another look at this?

**Review by tibetsprague — APPROVED** [review]

**Comment by tibetsprague** [comment]
no looks good, except for the tests failing! @dcetlin the way to fix is run yarn test and then press u to update the failing snapshots. i could do it but would be good for you to go through that process

**Comment by tibetsprague** [comment]
decided to just fix the test and merge! wheee!

**Pull request merged**
