### PR TITLE
413 add locations to posts

### PR DESCRIPTION
**Pull request by tibetsprague**
Fixes https://github.com/Hylozoic/hylo-evo/issues/413

### CODE REVIEW

**Comment by cpolitano** [comment]
Getting `Failed prop type: Invalid prop `post.location` of type `string` supplied to `PostCard`, expected `object`.` after creating a post with a specific address.

**Comment by cpolitano** [comment]
If a post has a location, do we indicate that anywhere on the post itself?

**Comment by tibetsprague** [comment]
@cpolitano no not yet. we need a design for that @brodeur. I will add a ticket for it

**Comment by cpolitano** [comment]
this is so amazing!!! 👍

**Comment by tibetsprague** [comment]
@clare i fixed the PostCard issue, and some more styling stuff, and i think this branch could be merged in now! unless we want to wait for @brodeur to do some designs for locations

**Comment by cpolitano** [comment]
I saw @brodeur get started on that, but I don't think we have to wait. Can you fix the merge conflict though?

**Comment by tibetsprague** [comment]
also fixes https://github.com/Hylozoic/hylo-evo/issues/423

**Pull request merged**
