### PR TITLE
632 skills to learn

### PR DESCRIPTION
**Pull request by tibetsprague**
Not my favorite solution but best i could figure out for now

Fixes https://github.com/Hylozoic/hylo-evo/issues/632

### CODE REVIEW

**Comment by lorenjohnson** [comment]
(See https://github.com/Hylozoic/hylo-node/pull/562#issuecomment-735419379)

**Comment by tibetsprague** [comment]
@lorenjohnson ready for review again

**Review by lorenjohnson — APPROVED** [review]
👍  Approving.

One note to address or consider: 

I'm wondering why not re-use `SkillsSection` vs copy / paste. 

This could be accomplished by moving the graphql into the root of `graphql/mutations/addSkill|addSkillToLearn` (etc), keeping `components/SkillsToLearn/SkillsToLearn.connector.js` which would attach those respective queries, and reusing everything else from `.../SkillsToLearn`. . . Or similar.

This is not a common pattern in our code, but something in the Holo fork we ended-up doing more often. The reuse here would be appropriate as the uniformity of the UX is on these two features what is desirable (at least for now).

**Comment by tibetsprague** [comment]
i did start by trying to reuse code but there are enough places where it would require awkward passing around of which type of skill is this and conditionals that it ended up feeling just as clean to copy even though there is significant code reuse. i am thinking about it again...

**Comment by tibetsprague** [comment]
ok code now re-used

**Pull request merged**
