### PR TITLE
Evo 1667 image carousel not listening to keyboard events

### LINKED ISSUE #1667: Image carousel not listening to keyboard events and aspect ratio off
When an image is clicked from a PostCard, the keyboard events are not connecting to the listener, only after the PostDetails are showing on the right-hand side and the PostCard image is clicked are the listeners connected.

So it must be kind of like a race condition.

### PR DESCRIPTION
**Pull request by KevinTriplett**
Closed #1667 

Two commits:
- removed an onClick that overrode the CardImageAttachments onClick
  - this means that clicking an image on a PostCard opens the ImageCarousel modal and not the PostDetail slide-out (so this might not be the way we want it to behave, we may want it to open the PostDetails and require another click/touch to open the ImageCarousel modal)
- fix a WebKit bug that caused the "others" thumbnail images to stretch

### CODE REVIEW

**Comment by KevinTriplett** [comment]
Third commit to fix tests failing CI due to difference in timezone

**Comment by KevinTriplett** [comment]
Okay, fixed now and ready for review

**Comment by KevinTriplett** [comment]
I'm going to mothball this, I just realized that clicking the image in the Card view should show the post details, not the image carousel.

**Review by tibetsprague — COMMENTED** [review]
ooh yay thank you!

**Pull request closed without merging**
