### PR TITLE
Add language detection and selector

### LINKED ISSUE #1475: Add language detector to front-end
https://github.com/i18next/i18next-browser-languageDetector

### PR DESCRIPTION
**Pull request by thomasgwatson**
Closes #1475

### CODE REVIEW

**Comment by tibetsprague** [comment]
is this ready to go? looks good to me

**Comment by thomasgwatson** [comment]
Yes. Mainly a question of how we want to sort out the translations. We
could deploy this, not announcing i18n, and then wait until we've got the
final translations before we announce and share that its changed

-Tom

**Comment by tibetsprague** [comment]
We could have a feature flag that turns this on or off with an environment variable. 
Also we should definitely deploy all this to staging first and test the hell out of it. 
Shall we merge this into the main translations branch and ill deploy that?
Or deploy that branch and test that first while we figure this one out?

**Comment by thomasgwatson** [comment]
Lets merge it all and deploy to staging

**Review by tibetsprague — APPROVED** [review]

**Pull request merged**
